//post 등록하기
POST http://localhost:3000/api/groups/36/posts
Content-Type: application/json

{
	"nickname": "real",
	"title": "telc",
	"content": "ffffxxf",
	"postPassword": "password1234",
	"groupPassword": "password123456",
	"imageUrl": "string",
	//"tags": ["tel", "100등"],  // 배열 형식
	"location": "string",
	"moment": "2024-02-21",
	"isPublic": true
}

###
//post 조회하기
GET http://localhost:3000/api/groups/36/posts?keyword=telc&isPublic=true

###
//비밀번호 확인
POST http://localhost:3000/api/posts/32/verify-password
Content-Type : application/json

{
  "password": "password1234"
}

###
//post 공개 여부 확인
GET http://localhost:3000/api/posts/32/is-public


###
//post 수정하기
PATCH http://localhost:3000/api/posts/32
Content-Type : application/json

{
	"nickname": "string",
	"title": "stringddddd",
	"content": "string",
	"postPassword": "password1234",
	"imageUrl": "string",
	//"tags": [ "string", "string" ],
	"location": "string",
	//"moment": "2024-02-21",
	"isPublic": true
}

###
//post 삭제하기
DELETE http://localhost:3000/api/posts/32
Content-Type : application/json

{
	"postPassword": "password1234"
}

###
//post 상세 조회
GET http://localhost:3000/api/posts/30


###
//post 공감 추가하기
POST http://localhost:3000/api/posts/30/like